services:
  mysqldb:
    image: mysql:8.0
    container_name: audiovisual-gestao-db-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file: .env
    networks:
      - techacademy-network
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./TechAcademy-5-Api-Audiovisual
    container_name: nest-js-app
    env_file: .env
    depends_on:
      - mysqldb
    networks:
      - techacademy-network

  frontend:
    build: ./gestao-audiovisual
    container_name: react-vite-app
    depends_on:
      - api
    networks:
      - techacademy-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
    networks:
      - techacademy-network

networks:
  techacademy-network:
    driver: bridge

volumes:
  mysql_data:
  dbeaver_data:
